platform :ios, '6.0'
xcodeproj './Getaway.xcodeproj'
pod 'MMDrawerController', '~> 0.4.0'
# pod 'iCarousel', '~> 1.7.4'
# pod 'Facebook-iOS-SDK'
# pod 'GPUImage', '~> 0.1.0'
pod 'FlatUIKit'
pod 'Reveal-iOS-SDK'
pod 'PullToRefresh'
pod 'FXBlurView'